// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOzQt_4YJQOksIpVYFWrF3GTiB1e8uA0',
    appId: '1:1097056844428:web:528094cdacb1a5705919a9',
    messagingSenderId: '1097056844428',
    projectId: 'attendance-app-project-92f92',
    authDomain: 'attendance-app-project-92f92.firebaseapp.com',
    storageBucket: 'attendance-app-project-92f92.firebasestorage.app',
    measurementId: 'G-99000S7T6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDeL9PdilZzI3RMAeU-JNfmM0JRed5-Q',
    appId: '1:1097056844428:android:da594fdc3df8acf45919a9',
    messagingSenderId: '1097056844428',
    projectId: 'attendance-app-project-92f92',
    storageBucket: 'attendance-app-project-92f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDuYlSzgoJZu60ztJ3lkQZbeWAIoNhMY',
    appId: '1:1097056844428:ios:0838be4b79692eab5919a9',
    messagingSenderId: '1097056844428',
    projectId: 'attendance-app-project-92f92',
    storageBucket: 'attendance-app-project-92f92.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDuYlSzgoJZu60ztJ3lkQZbeWAIoNhMY',
    appId: '1:1097056844428:ios:0838be4b79692eab5919a9',
    messagingSenderId: '1097056844428',
    projectId: 'attendance-app-project-92f92',
    storageBucket: 'attendance-app-project-92f92.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtOzQt_4YJQOksIpVYFWrF3GTiB1e8uA0',
    appId: '1:1097056844428:web:1626faef77e36c1c5919a9',
    messagingSenderId: '1097056844428',
    projectId: 'attendance-app-project-92f92',
    authDomain: 'attendance-app-project-92f92.firebaseapp.com',
    storageBucket: 'attendance-app-project-92f92.firebasestorage.app',
    measurementId: 'G-CXPNRGV78M',
  );
}
